language: python
sudo: false

env:
  matrix:
    - PYTHON=3.5 IPYTHON_KERNEL=python3

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-environment -c conda-forge python=$PYTHON numpy>=1.17.0 flake8 pytest scipy multipledispatch cloudpickle numba dask mock scikit-learn jupyter sparse>=0.7.0
  - source activate test-environment
  - pip install git+https://github.com/dask/dask
  - conda list

  # Install dask-glm
  - pip install --no-deps -e .

script:
  - py.test dask_glm
  - flake8 dask_glm

notifications:
  email: false
