version: 2
jobs:
  py36:
    docker:
      - image: continuumio/miniconda:latest
    environment:
      PYTHON: "3.6"
      ENV_NAME: "dask-ml-test"
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-3.6-{{ checksum "ci/environment-3.6.yml" }}
      - run:
          name: configure conda
          command: ./ci/install-circle.sh
      - run:
          command: |
            source activate ${ENV_NAME}
            pytest --cov=dask_ml tests
      - run:
          command: |
            source activate ${ENV_NAME}
            flake8
            black --check .
            isort --recursive --check-only
            codecov
      - save_cache:
          key: deps-{{ .Branch }}-3.6-{{ checksum "ci/environment-3.6.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"

  # Python 2.7 build
  py27:
    docker:
      - image: continuumio/miniconda:latest
    environment:
      PYTHON: "2.7"
      ENV_NAME: "dask-ml-test"
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-2.7-{{ checksum "ci/environment-2.7.yml" }}
      - run:
          name: configure conda
          command: ./ci/install-circle.sh
      - run:
          command: |
            source activate ${ENV_NAME}
            pytest tests
      - run:
          command: |
            source activate ${ENV_NAME}
      - save_cache:
          key: deps-{{ .Branch }}-2.7-{{ checksum "ci/environment-2.7.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"

  # scikit-learn dev build
  sklearn_dev:
    docker:
      - image: continuumio/miniconda:latest
    environment:
      PYTHON: "3.6"
      ENV_NAME: "dask-ml-test"
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-sklearn_dev-{{ checksum "ci/environment-3.6.yml" }}
      - run:
          name: configure conda
          command: ./ci/install-circle.sh
      - run:
          name: install sklearn-dev
          command: |
            source activate ${ENV_NAME}
            conda uninstall -y --force scikit-learn
            pip install --pre git+https://github.com/scikit-learn/scikit-learn
      - run:
          command: |
            source activate ${ENV_NAME}
            pytest tests
      - save_cache:
          key: deps-{{ .Branch }}-sklearn_dev-{{ checksum "ci/environment-3.6.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"

workflows:
  version: 2
  build_and_test:
    jobs:
      - py36
      - py27
      - sklearn_dev
