name: dask-ml-test
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - coverage
  - flake8
  - graphviz
  - heapdict
  - ipykernel
  - ipython
  - isort
  - multipledispatch
  - mypy
  - nbsphinx
  - nomkl
  - nose
  - numba
  - numpy
  - numpydoc
  - pandas
  - psutil
  - pytest
  - pytest-cov
  - pytest-mock
  - python=3.6.6
  - sortedcontainers
  - scikit-learn>=0.21.3
  - scipy
  - sparse
  - sphinx==1.8.5
  - sphinx_rtd_theme
  - sphinx-gallery
  - tensorflow
  - testpath<0.4
  - tornado
  - toolz
  - xgboost
  - zict
  - pip
  - dask
  - dask-glm
  - distributed
  - dask-xgboost
  - pip:
    - git+https://github.com/dask/dask-tensorflow.git
    - dask_sphinx_theme >=1.1.0
    - graphviz
