name: dask-ml-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - coverage
  - flake8
  - graphviz
  - heapdict
  - ipykernel
  - ipython
  - isort==4.3.21
  - multipledispatch
  - mypy
  - nbsphinx
  - nomkl
  - nose
  - numba
  - numpy
  - numpydoc
  - pandas
  - psutil
  - pytest
  - pytest-cov
  - pytest-mock
  - python=3.9
  - sortedcontainers
  - scikit-learn>=0.23.1
  - scipy
  - sparse
  - sphinx==1.8.5
  - sphinx_rtd_theme
  - sphinx-gallery
  - testpath<0.4
  - tornado
  - toolz
  - xgboost
  - zict
  - pip
  # dask 2021.3.0 introduced a regression which causes tests to fail.
  # The issue has been resolved upstream in dask and will be included
  # in the next release. We temporarily apply a dask version contraint
  # to allow CI to pass
  - dask !=2021.3.0
  - dask-glm
  - dask-xgboost
  - pip:
    - dask_sphinx_theme >=1.1.0
    - graphviz
