name: dask-ml-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - coverage
  - graphviz
  - heapdict
  - ipykernel
  - ipython
  - multipledispatch
  - mypy
  - nbsphinx
  - nomkl
  - nose
  - numba
  - numpy
  - numpydoc
  - pandas
  - psutil
  - python=3.10
  - sortedcontainers
  - scikit-learn >=1.2.0
  - scipy
  - sparse
  - sphinx
  - sphinx_rtd_theme
  - sphinx-gallery
  - tornado
  - toolz
  - zict
  - pip
  - dask
  - dask-glm
  - pip:
    - dask-sphinx-theme >=3.0.0
    - graphviz
