name: dask-ml-test
channels:
  - defaults
  - conda-forge
dependencies:
  - black
  # Cython for building scikit-learn dev. Switch to nightly
  # when this is resolved:
  # https://github.com/scikit-learn/scikit-learn/issues/9485
  - Cython
  - coverage
  - codecov
  - flake8
  - graphviz
  - heapdict
  - ipykernel
  - ipython
  - isort
  - multipledispatch
  - nbsphinx
  - nomkl
  - nose
  - numba
  - numpy
  - numpydoc
  - pandas
  - psutil
  - pytest
  - pytest-cov
  - pytest-mock
  - python=3.6.6
  - sortedcontainers
  - scikit-learn>=0.20.0
  - scipy
  - six
  - sparse
  - sphinx
  - sphinx_rtd_theme
  - sphinx-gallery
  - tensorflow
  - testpath<0.4
  - tornado
  - toolz
  - xgboost
  - zict
  - pip:
    - dask-glm
    - git+https://github.com/dask/dask.git
    - git+https://github.com/dask/distributed.git
    - git+https://github.com/dask/dask-tensorflow.git
    - git+https://github.com/dask/dask-xgboost.git
    - dask_sphinx_theme >=1.1.0
    - graphviz
