name: dask-ml-test
channels:
  - defaults
  - conda-forge
dependencies:
  - coverage
  - flake8
  - graphviz
  - heapdict
  - ipython
  - multipledispatch
  - nbsphinx
  - nomkl
  - nose
  - numba
  - numpy=1.15.0
  - numpydoc
  - pandas
  - psutil
  - pytest
  - pytest-cov
  - pytest-mock
  - python=2.7.14
  - sortedcontainers
  - scikit-learn>=0.20.0
  - scipy
  - six
  - sparse
  - sphinx
  - sphinx_rtd_theme
  - sphinx-gallery
  - tensorflow
  - testpath<0.4
  - tornado
  - toolz
  - xgboost
  - zict
  - pip:
    - dask-glm
    - git+https://github.com/dask/dask.git
    - git+https://github.com/dask/distributed.git
    - git+https://github.com/dask/dask-tensorflow.git
    - git+https://github.com/dask/dask-xgboost.git
    - graphviz
